spring:
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: false
  profiles:
    active: local

decorator:
  datasource:
    p6spy:
      enable-logging: true


springdoc:
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret:
    key: bXktdmVyeS1zdHJvbmctand0LXNlY3JldC1rZXktdGhhdC1pcy1sb25nLWVub3VnaA==

aws:
  s3:
    bucket: tdd-bucket-01
    region: ap-northeast-2
  cloudfront:
    domain: https://d2omdjdfhddmrs.cloudfront.net